### ISSUE TITLE
Search multiple keyword

### ISSUE THREAD

**Issue by microdevil** [jeancroy/FuzzySearch#1]
Hi...

Beforehand, I am really thank to you because of creating this library. This library help me to search keyword based on similarity.
My question :
1. is this supporting for searching multiple keyword ? I wanna search keyword with "R and B" and "R&B"
2. is this supporting for searching some keyword like "R and B" => "R&B" ? I wanna improve my searching like 1 => one or 12 => twelve. 

"Sorry for my bad grammar"
Thanks

**Comment by jeancroy** [comment]
1) Yes it is.
2) This will not do substitution in the query '&' => 'and'
However it allow to search in list, so you can define synonyms

````js
Genre = [
{Name: "R&B", Keywords ["R&B", "R and B", "Rythm and Blues"] }
{Name: "Rock", Keywords ["Rock&Rolls", "Rock'nRolls"] }
]
````

**Comment by microdevil** [comment]
Hi @jeancroy 
Thanks for your fast answer

Is this code for searching multiple keyword ?

```
var data = ["survey","surgery","insurgence"];
var searcher = new FuzzySearch({source:data});
var query_1 = "keyword_1";
var query_2 = "keyword_2"
var result_1 = searcher.search(query_1, query_2);
// Or 
var result_2 = searcher.search([query_1, query_2]);
```

I just wanna confirm that my code on the right place


Thanks...

**Comment by jeancroy** [comment]
Multiple keyword like sentence, separate them by space
