### ISSUE TITLE
Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by Hasan-git** [jeancroy/FuzzySearch#18]
@jeancroy  Thank you for this wonderful library!!!
 indeed, It's a buried treasure just need some attention.

I have experienced some issues when a property is null

![image](https://user-images.githubusercontent.com/8820596/48971889-aefd6400-f028-11e8-85d0-218a0ab26cbe.png)

**Comment by jeancroy** [comment]
Thanks for the support !
So the desired behavior is skip indexing of this field on this object ?

**Comment by Hasan-git** [comment]
For me, I just fixed it for now by checking if value is null then push an empty string !
else list.push(obj.toString()); -> else list.push(obj != null ? obj.toString() : '');
actually, I don't know if its the best solution, but I need a fast solution while null values are so common in my case.

**Comment by jeancroy** [comment]
Hi, I just pushed something that I think address your issue.

https://github.com/jeancroy/FuzzySearch/commit/cbcdd8307d70a209b1cbf17a535158d5c21840d7

**Comment by Hasan-git** [comment]
Great job !!
