### ISSUE TITLE
synonyms substitute

### ISSUE THREAD

**Issue by amod400** [jeancroy/FuzzySearch#25]
Hello Team, 

Quick question, do we have a synonym substitute that we could do 
for example `'lat' -> 'Geo Coordinates``

--Thanks B

**Comment by jeancroy** [comment]
The way I usually handle this in my own projects is that entries can have a
item.keywords attribute, which is an array of strings of different ways to
call this entry in order of preference.
Then if you want to explain the match there's a GUI helper to find which of
the keywords produced a match and communicate that to the user if you. I
think I have one example setup like this.

An alternative design is to first use the above method to search a synonym
bank, then augment original query with the result of this synonym search.
You can then proceed to search original entries with the augmented query.


Jean Christophe Roy
