### ISSUE TITLE
How can i do it with post method? and mysql

### ISSUE THREAD

**Issue by canomi** [jeancroy/FuzzySearch#28]
I need data from database via post method, so how can i do that?
I've just try as follow:
`<script>
    var fuzzyhound = new FuzzySearch();

        $('#demo-query').typeahead({
            minLength: 2,
            highlight: false //let FuzzySearch handle highlight
        },
        {
            name: 'movies',
            source: fuzzyhound,
            templates: {
                suggestion: function(result){return "<div>"+fuzzyhound.highlight(result)+"</div>"}
            }
        });
    $.ajaxSetup({cache: true});
    function setsource(url, keys, output) {
    $.post( url, { query:query,_csrf:_csrf })
        .done(function( response ) fuzzyhound.setOptions({
                source: response,
                keys: keys,
                output_map: output
            })
        });    
    }
    setsource("test.php");
</script>`
How can i define the keyword (query)?
Thanks

**Comment by jeancroy** [comment]
> How can I define the keyword (query) ?

So at the base, the thing is setup for a client side list of options.

When you do this `source: fuzzyhound,` we are really using the __ttAdapter interface.
https://github.com/jeancroy/FuzzySearch/blob/master/src/optional/ui.js#L85

you can build your own interface that'll get access to the query, and eventually change source available for autocomplete.
