### ISSUE TITLE
how do you select the matcing items?

### ISSUE THREAD

**Issue by halukkaramete** [jeancroy/FuzzySearch#31]
Hi, when the algorithm suggests a few items, how do you select one so it is added into the textbox or submit that selection to my server?   By default, when I click/choose an item, the text box gets cleared immediately and the suggestions drop-down disappears.  I would like it to behave like a typical Google search... In google, when you type, google makes some auto-suggestions, and as soon as you select an item on the suggestions list, you end up firing a Google search for that selection.   Is there something like onClick, onSelect type hook, that passes the selection to a js function as inout and from there, I do whatever I can???

**Comment by jeancroy** [comment]
So in general there's 3 things.

1) Recommendation Engine
2) UI control
3) Integration of the UI control on your website.

This project is (1) there's no UI control (2) included in this project, you have to provide your own.

Most UI controls have exact search recommendation built in.
Some UI control allow to plug your own recommendation engine and that's when this library is useful.

After that the UI control should provide you with an event (onchange, onselect or similar) and it's up to you to hook that to an action that submit a form, or do an ajax call etc. This is (3)

**Comment by halukkaramete** [comment]
Thank you Jean for your reply. I'm sorry but re-opening but your tool is amazing.  
I've already implemented a dynamic autocomplete using Bootstrap Typeahead JS across a 1.6M records MySQL table and it works darn fast HOWEVER, it does not have that cool searching technology which finds words in sentences, not necessarily in order. But how do you connect the two?   I got this 

```
$('input.typeahead').typeahead({
      items: 20,
      minLength: 1,
	    source:  function (query, process) {
                        return $.get('https:// ... com/search1.php', { query: query }, 
                            function (data) {
        		        data = $.parseJSON(data);
	                        return process(data);
	                    });
	      }
	});

```

but you have something like this: 

$('#typeahead-input').typeahead({
            minLength: 2,
            highlight: false //let FuzzySearch handle highlight
        },
        {
            name: 'books',
            source: fuzzyhound,
            templates: {
                suggestion: function(result){return "<div>"+fuzzyhound.highlight(result.title)+" by "+fuzzyhound.highlight(result.author)+"</div>"}
            }
        });

Is it as simple as these 2 liners where I map my JSON object properties properly? 

var books = [{"title":"First Book", "author":"John Doe"}, {"title":"...", "author":"..."}];
var fuzzyhound = new FuzzySearch({source:books, keys:["title","author"] });

**Comment by halukkaramete** [comment]
I think your algorithm can solve this issue: 

Try "uhud is" in this URL pls: https://www.islamicity.org/quransearch/lab/scrape-sunnah-com/ajax.html  ( it will match "uhud is a mountain which loves" ) 
In this implementation, the DB has 1.6M records and see how fast it is. 
But then try "uhud loves".  There will be No match. Why? that is because of the extra words in between uhud and loves which are ("a mountain which"). But your tool can handle that barrier as a piece of cake but I just cannot figure out how to connect the two? If I can connect the too, a dream will come true.

**Comment by halukkaramete** [comment]
please do not reply yet. let me hassle with this myself going thru all the docs you have and then I'll share with you where I fail, if I fail. thx.
