### ISSUE TITLE
debug mode

### ISSUE THREAD

**Issue by halukkaramete** [jeancroy/FuzzySearch#33]
Hi Jean,
Just to see which item matched with what score, is it possible modify the code so I can see numbers like 

one flew over the cuckoos nest (1975) **@ 78**          // biggest score in this case was 78 
one false move ( 1992) **54**   // here the score is 54 and so on... 
... 
last item **20** // here the last item's score is 20 because field_good_enough setting is set to 20

If I see what score items are matching, I can play with field_good_enough more effectively to fine tune the numbers.

**Comment by jeancroy** [comment]
Yes see output map option to include an object with score

See https://github.com/jeancroy/FuzzySearch#get-score-detail-searchresult-object
